export const WISH_LIST_NAME = '#profile-list-name'
export const TITLE = '#productTitle'
export const PRICE = '//span[text() = "Kindle版 (電子書籍)"]'
export const REAL_PRICE = '#print-list-price'
export const THUMBNAIL = '#ebooksImgBlkFront'
