name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build
        run: yarn && yarn build
  deploy-frontend-remix:
    needs: build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./apps/frontend-remix
    steps:
      - name: deploy
        run: ls -l ./
  deploy-backend-heroku:
    needs: build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./apps/backend-heroku
    steps:
      - name: deploy
        run: ls -l ./